### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by umerk44** [almalence/OpenCamera#2]
When i launch app i got this.

03-21 12:55:11.064: E/AndroidRuntime(7334): FATAL EXCEPTION: main
03-21 12:55:11.064: E/AndroidRuntime(7334): java.lang.UnsatisfiedLinkError: Couldn't load utils-image from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.almalence.opencam-1.apk,libraryPath=/data/app-lib/com.almalence.opencam-1]: findLibrary returned null
03-21 12:55:11.064: E/AndroidRuntime(7334):     at java.lang.Runtime.loadLibrary(Runtime.java:355)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at java.lang.System.loadLibrary(System.java:525)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at com.almalence.util.Util.<clinit>(Util.java:752)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at com.almalence.plugins.capture.panoramaaugmented.PanoramaAugmentedCapturePlugin.getAmountOfMemoryToFitFrames(PanoramaAugmentedCapturePlugin.java:884)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at com.almalence.plugins.capture.panoramaaugmented.PanoramaAugmentedCapturePlugin.onDefaultsSelect(PanoramaAugmentedCapturePlugin.java:263)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at com.almalence.opencam.PluginManager.SelectDefaults(PluginManager.java:1273)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at com.almalence.opencam.MainScreen.setupCamera(MainScreen.java:879)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at com.almalence.opencam.MainScreen$8.onFinish(MainScreen.java:676)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:118)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at android.os.Handler.dispatchMessage(Handler.java:99)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at android.os.Looper.loop(Looper.java:176)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at android.app.ActivityThread.main(ActivityThread.java:5419)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at java.lang.reflect.Method.invokeNative(Native Method)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at java.lang.reflect.Method.invoke(Method.java:525)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
03-21 12:55:11.064: E/AndroidRuntime(7334):     at dalvik.system.NativeStart.main(Native Method)

**Comment by caowen** [comment]
when build in AS,  i met a  problem

   Process: com.almalence.opencam, PID: 19022
    java.lang.UnsatisfiedLinkError: Couldn't load utils-image from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.almalence.opencam-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.almalence.opencam-1, /vendor/lib, /system/lib]]]: findLibrary returned null
            at java.lang.Runtime.loadLibrary(Runtime.java:358)
            at java.lang.System.loadLibrary(System.java:526)
            at com.almalence.plugins.capture.panoramaaugmented.VfGyroSensor.<clinit>(VfGyroSensor.java:331)
            at com.almalence.plugins.vf.gyro.GyroVFPlugin.onResume(GyroVFPlugin.java:174)
            at com.almalence.opencam.PluginManagerBase.onResume(PluginManagerBase.java:481)
            at com.almalence.opencam.MainScreen$5.onFinish(MainScreen.java:1108)
            at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:118)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5131)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by almalence** [comment]
Please check console output. Seems you have error in native part.
