### ISSUE TITLE
Can not open A Better Camera

### ISSUE THREAD

**Issue by xu6148152** [almalence/OpenCamera#23]
When I open the application , it will crash
the following is its error message

[2015-01-14 13:56:33 - ddms] Can't bind to local 8617 for debugger
[2015-01-14 13:56:33 - ddmlib] Broken pipe
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
	at com.android.ddmlib.JdwpPacket.writeAndConsume(JdwpPacket.java:213)
	at com.android.ddmlib.Client.sendAndConsume(Client.java:642)
	at com.android.ddmlib.HandleHeap.sendREAQ(HandleHeap.java:348)
	at com.android.ddmlib.Client.requestAllocationStatus(Client.java:488)
	at com.android.ddmlib.DeviceMonitor.createClient(DeviceMonitor.java:831)
	at com.android.ddmlib.DeviceMonitor.openClient(DeviceMonitor.java:799)
	at com.android.ddmlib.DeviceMonitor.processIncomingJdwpData(DeviceMonitor.java:759)
	at com.android.ddmlib.DeviceMonitor.deviceClientMonitorLoop(DeviceMonitor.java:648)
	at com.android.ddmlib.DeviceMonitor.access$100(DeviceMonitor.java:44)
	at com.android.ddmlib.DeviceMonitor$3.run(DeviceMonitor.java:576)

Please fix it,thank you!

**Comment by almalence** [comment]
Do not see any A Better Camera specific problem in your report. Problem with debugger or driver possibly.

What is your Device, Android version? Under what OS you're working? Was apk file built or not? More details!

**Comment by xu6148152** [comment]
motoX 4.4.4
